version: '3'
services:

  nerdvend:
    container_name: ${APP_NAME}_nerdvend
    build:
      context: java.Dockerfile
    depends_on:
      - database
    ports:
      - 8080:8080
    networks:
      - nerdvend_network

  database:
    image: postgres:15.8-alpine
    container_name: ${APP_NAME}_postgres
    restart: always
    volumes:
      - ./database:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    networks:
      - nerdvend_network

networks:
  nerdvend_network:
    driver: bridge
